spring.application.name=pqrsprocesadorms
spring.datasource.url=jdbc:postgresql://localhost:5432/ucoshopdb
spring.datasource.username=postgres
spring.datasource.password=j5389140
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_cregation=true

# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=false

#myquestion
procesadorpqrs.mispreguntas.crear-qn=procesadorpqrs.mispreguntas.crear
procesadorpqrs.mispreguntas.crear-ex=procesadorpqrs.mispreguntas
procesadorpqrs.mispreguntas.crear-rk=crear

procesadorpqrs.mispreguntas.actualizar-qn=procesadorpqrs.mispreguntas.actualizar
procesadorpqrs.mispreguntas.actualizar-ex=procesadorpqrs.mispreguntas
procesadorpqrs.mispreguntas.actualizar-rk=actualizar

procesadorpqrs.mispreguntas.corregir-qn=procesadorpqrs.mispreguntas.corregir
procesadorpqrs.mispreguntas.corregir-ex=procesadorpqrs.mispreguntas
procesadorpqrs.mispreguntas.corregir-rk=corregir

procesadorpqrs.mispreguntas.respuesta-actualizar-qn=procesadorpqrs.mispreguntas.respuesta.actualizar
procesadorpqrs.mispreguntas.respuesta-actualizar-ex=procesadorpqrs.mispreguntas.respuesta
procesadorpqrs.mispreguntas.respuesta-actualizar-rk=respuesta.actualizar