spring.application.name=pqrsprocesadorms
spring.datasource.url=jdbc:postgresql://localhost:5432/ucoshopdb
spring.datasource.username=postgres
spring.datasource.password=000
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_cregation=true

# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=false

#myquestion
mensaje.myquestion.crear.exchange-name=procesadorpqrs.myquestion.crear.ex
mensaje.myquestion.crear.routing-key=procesadorpqrs.myquestion.crear.rk
mensaje.myquestion.crear.queue-name=procesadorpqrs.myquestion.crear.qu